<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit93dd39a792e7a59d085f098019b91028
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SquareConnect\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SquareConnect\\' => 
        array (
            0 => __DIR__ . '/..' . '/square/connect/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit93dd39a792e7a59d085f098019b91028::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit93dd39a792e7a59d085f098019b91028::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
